version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  run-test:
    docker:
      - image: cimg/python:3.8.19
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Setting PYTHONPATH
          command: echo 'export PYTHONPATH="${PYTHONPATH}:src"' >> $BASH_ENV
      - run:
          name: Run tests
          command: pytest
  build-dev:
    docker:
      - image: cimg/python:3.8.19
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Change work directory
          command: |
            cd src
            rm -rf dist/
            rm -rf deconfig.egg-info/
      - run:
          name: Setting environment variables
          command: |
            echo 'export TWINE_USERNAME="${TWINE_DEV_USERNAME}"' >> $BASH_ENV
            echo 'export TWINE_PASSWORD="${TWINE_DEV_PASSWORD}"' >> $BASH_ENV
            echo 'export TWINE_REPOSITORY="${TWINE_DEV_REPOSITORY}"' >> $BASH_ENV
      - run:
          name:
          command: |
            echo 'export DEV_VERSION="$(python3 -c "import deconfig; print(deconfig.__version__)").$BUILD_TIME"'
            python3 -m build
            python3 -m twine upload --repository testpypi dist/*


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  run-tests: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - run-test
      - build-dev:
          requires:
            - run-test
          filters:
            branches:
              only:
                - main
                - /^release.*/
                - /^circle-ci-setup-.*/
